apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        db: mssql
    spec:
      containers:
      - name: order
        image: eyujy/orderapi:v4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "200m"
            memory: "64Mi"  
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"  
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password  
        - name: MSSQL_HOST
          value: "db-mssql"
        - name: MSSQL_PORT
          value: "1433"  
        - name: MSSQL_USER
          valueFrom:
            secretKeyRef:
              name: mssql
              key: user
        - name: MSSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: password
        - name: MSSQL_DATABASE
          value: "Orders" 
        ports:
          - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: order
  annotations:
   konghq.com/plugins: twelve-per-min
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 65
